### ISSUE TITLE
Support futures

### ISSUE THREAD

**Issue by kw217** [AlexPikalov/cdrs#130]
Hi - are there any plans to integrate cdrs with futures and streams (https://crates.io/crates/futures)? At the moment it looks like query execution is blocking, and ties up both a thread and a TCP connection for the duration of the query (please correct me if I'm wrong). For high-performance, scalable applications it is desirable to support asynchronous operation, and futures seems to be a good way of achieving this in Rust. Thanks.

**Comment by AlexPikalov** [comment]
@kw217 
sorry for the delay, there is a plan to make CDRS async and non-blocking of course. I think it makes sense to start this after we have a stable process of making requests and mapping results into Rust. I feel that at the moment we're pretty close to that, so maybe one of nearest versions will have async, non-blocking nature.

**Comment by AlexPikalov** [comment]
@kw217 
I tend to think that it's a good idea to follow a way which let say [rust-postgres](https://github.com/sfackler/rust-postgres) goes - to have a standalone crate for a client based on Tokio or whatever else async io crate; and to keep a main crate as tiny as possible.

From my end, I work on such standalone version which wraps CDRS into Futures, but feel free to try to create your own because my work is in progress.

I'm closing this issue so far.
