### ISSUE TITLE
Session mutability

### ISSUE THREAD

**Issue by pimeys** [AlexPikalov/cdrs#214]
Hi,

I'm holding an instance of cdrs accessible from multiple threads and I can't really wrap my head around how to share it and still be able to use `Session`. Almost all methods in `Session` require a mutable reference, which I definitely will not have in my case.

I'm currently evaluating the 2.0 pre versions and this is a blocking issue for me to move forward. Is there some way to get a mutable `Session` from a pool without actually forming a new connection every time one wants to query Cassandra?

**Comment by AlexPikalov** [comment]
@pimeys Thank you for reporting the issue.

I'll try to find out a solution similar to #201 Will keep you updated in this thread.

**Comment by AlexPikalov** [comment]
@pimeys I was thinking about your case. With my current understanding of your situation [`r2d2::Pool`](https://docs.rs/r2d2/0.8.2/r2d2/struct.Pool.html) may help. This might be a pool of `cdrs::Session`. And usage could be the same as for [Postges](https://github.com/sfackler/r2d2-postgres). What you'd need to do is just to implement [`r2d2::ManageConnection`](https://docs.rs/r2d2/0.8.2/r2d2/trait.ManageConnection.html). In this trait, `Connection = cdrs::Session` and `Error = cdrs::Error`. This pool will maintain number of sessions (connections) available for usage in threads and reuse those ones that were released.

Please let me know if it unblocks you.

Meanwhile, I'm working on solution which would allow to not have mutable session instance.

**Comment by ernestas-poskus** [comment]
```rust
use cdrs::authenticators::NoneAuthenticator;
use cdrs::compression::Compression;
use cdrs::connection_manager::ConnectionManager;
use cdrs::transport::TransportTcp;
use r2d2::Pool;
use std::time::Duration;

use config;

lazy_static! {
    static ref CASSANDRA: Pool<ConnectionManager<NoneAuthenticator, TransportTcp>> = {
        let transport: TransportTcp = TransportTcp::new(config::CASSANDRA_IPS)
            .expect("Failed to initialize Cassandra tranport");

        let manager = ConnectionManager::new(transport, NoneAuthenticator, Compression::None);

        Pool::builder()
            .max_size(config::CASSANDRA_DB_POOL_SIZE)
            .min_idle(Some(config::CASSANDRA_DB_POOL_MIN_IDLE))
            .test_on_check_out(config::CASSANDRA_DB_POOL_TEST_ON_CHECKOUT)
            .idle_timeout(Some(Duration::from_secs(
                config::CASSANDRA_DB_POOL_IDLE_TIMEOUT,
            )))
            .max_lifetime(Some(Duration::from_secs(
                config::CASSANDRA_DB_POOL_MAX_LIFETIME,
            )))
            .connection_timeout(Duration::from_secs(
                config::CASSANDRA_DB_POOL_CONNECTION_TIMEOUT,
            ))
            .build(manager)
            .expect("Failed to initialize Cassandra connection pool")
    };
}

pub fn cassandra() -> Pool<ConnectionManager<NoneAuthenticator, TransportTcp>> {
    CASSANDRA.clone()
}

#[test]
fn test_connection() {
    use db::cassandra;
    cassandra(); // r2d2 Pool does valid()
}
```

this is an actual production example how to use r2d2 pool of connections, to acquire connection just call

```rust
try!(db::cassandra().get()) OR db::cassandra().get()?
```

**Comment by AlexPikalov** [comment]
@pimeys pimeys

For version 1 it looks pretty straight forward to deal with. As @ernestas-poskus  mentioned cdrs Connection Manager could be leveraged.

However with version 2 API it's not that obvious because session is built around cluster of nodes + load balancing. In this case for me it makes sense to talk about pools of connection to each of nodes in a cluster. In other case (pool of sessions) load balancing works awkward. For example, in case of Round Robin LB and pool size of 10 first 10 request will go directly to the first node despite we would like them to be spread through the nodes in the cluster.

As an option you can consider something similar to Actix's approach to work with DBs https://actix.rs/docs/databases/. What does it do is just manually creates few instances of db an put each connection into a separated thread then communicate through sending messages back and forth.

In a spare time you can check out if https://github.com/AlexPikalov/cdrs/pull/216 resolves your problem with session mutability
