### ISSUE TITLE
Connection pooling with v2.0.0?

### ISSUE THREAD

**Issue by jgrimes** [AlexPikalov/cdrs#219]
It seems like the `ConnectionManager` that could be used with `r2d2` was removed with v2.0.0 -- what are people currently doing for connection pooling?

I saw that in this issue https://github.com/AlexPikalov/cdrs/issues/217 that one of the problems with combining round-robin load balancing and a connection pool in the "naive" way is that the first node in the list will basically have _n_ connections open to it before moving on to the next one, which isn't ideal -- but I am also wondering if this really matters under load? Reasoning being that there is plenty of work to go around, so it doesn't matter if one node is initially connected to more often and that it would ultimately balance out.

**Comment by AlexPikalov** [comment]
Actually, v2.0.0 is still under development. #217 is a work in progress.

It's difficult to say without real measurement how much such implementation will impact this first node, but for me it seems that it will. I'd like to have connection polling per node but not session polling. Otherwise round robin behaviour will be pretty confusing, won't it?
