### ISSUE TITLE
panic: General("List should not be empty") when using SELECT, INSERT is fine

### ISSUE THREAD

**Issue by ernestas-poskus** [AlexPikalov/cdrs#282]
Have a problem with nested UDT SELECT query (INSERT is fine, verified data with cqlsh shell).

I use scylla database.

From backtrace looks like this place panics

```
macro_rules! list_as_rust {
    ($($into_type:tt)+) => (
        impl AsRustType<Vec<$($into_type)+>> for List {
            fn as_rust_type(&self) -> Result<Option<Vec<$($into_type)+>>> {
                match self.metadata.value {
                    Some(ColTypeOptionValue::CList(ref type_option)) |
                    Some(ColTypeOptionValue::CSet(ref type_option)) => {
                        let type_option_ref = type_option.as_ref();
                        let convert = self
                            .map(|bytes| {
                                as_rust_type!(type_option_ref, bytes, $($into_type)+)
                                    .unwrap()
                                    // item in a list supposed to be a non-null value.
                                    // TODO: check if it's true
                                    .unwrap()
                            });

                        Ok(Some(convert))
                    },
                    _ => Err(Error::General(format!("Invalid conversion. \
                            Cannot convert {:?} into List (valid types: List, Set).",
                            self.metadata.value)))
                }
            }
        }
    );
}
```

```
                                as_rust_type!(type_option_ref, bytes, $($into_type)+)
                                    .unwrap()
                                    // item in a list supposed to be a non-null value.
                                    // TODO: check if it's true
                                    .unwrap()
```

.unwrap in particular. Although I don't insert empty list (Vec) I assume it should initialize empty Vec on Rust side or did I misunderstood something?

**Comment by AlexPikalov** [comment]
Hi @ernestas-poskus ,

Thanks for submitting the issue!
If you don't submit an empty list I assume that there will be value [`NotSet`](https://github.com/AlexPikalov/cdrs/blob/master/src/types/value.rs#L21) returned by a server. Thus https://github.com/AlexPikalov/cdrs-helpers-derive/blob/master/src/common.rs#L74 will be not Ok.

If there is a case for you that for some value no-value can be submitted you can try to have `Option<Vec<YourType>>` as a type for this field instead of `Vec`. CDRS should tackle it and there shouldn't be any panic. IMO it describes your data nature more precisely, you'll just get `None`. I believe that such sort of result interpretation as `None -> vec![]` should be on the application side, not on a driver.

**Comment by ernestas-poskus** [comment]
Thank you for reply, value is not empty and I read instantly after write.. Anyway seems like it was Scylla issue after updating to latest docker version everything works as expected :man_shrugging:. 

Seems like an issue was with UDT TYPE, columns in nested UDT TYPE, Scylla cutoff last 2 columns, therefore, SELECT was failing although INSERT was successful.

Thanks for help :bowing_man:.

Please include patreon link or sth, I would like to buy you a beer :beer:.

**Comment by AlexPikalov** [comment]
@ernestas-poskus 
Glad to know it's working know. It's my pleasure to help 🙂 
PS: will consider adding Patreon 😄
